services:
  app-server:
    build: ./backend/
  dashboard:
    build: ./dashboard/
    ports:
      - "80:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rs648